version: '3.1'

services:
  
  # http://localhost:9100
  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"
  
  # http://localhost:9090
  prometheus:
    image: prom/prometheus:v2.26.1
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter
  
  # http://localhost:9093
  alert-manager:
    image: prom/alertmanager
    volumes:
      - "./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
      
 # http://localhost:3000
  grafana:
    image: grafana/grafana:7.5.6
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data: